apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: apiserver-vip
  namespace: kube-system
  labels: 
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        name: kube-keepalived-vip
      namespace: kube-system
    spec:
      hostNetwork: true
      containers:
        - image: gcr.io/google_containers/kube-keepalived-vip:0.9
          name: kube-keepalived-vip
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubeconfigs
              readOnly: true
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /dev
              name: dev
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # to use unicast
          command: 
          #- /bin/bash
          args:
          #- -c
          #- "sleep 999999"
          - --services-configmap=kube-system/apiserver-vip
          - --v=2
          - --logtostderr
          - --stderrthreshold=2
          - --namespace=default
          - --certificate-authority=/etc/kubernetes/ssl/ca.pem
          - --client-key=/etc/kubernetes/ssl/apiserver-key.pem
          - --client-certificate=/etc/kubernetes/ssl/apiserver.pem
          # unicast uses the ip of the nodes instead of multicast
          # this is useful if running in cloud providers (like AWS)
          #- --use-unicast=true
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: kubeconfigs
          hostPath:
            path: /etc/kubernetes
      nodeSelector:
        type: controller
