#cloud-config

coreos:
  update:
    reboot-strategy: "off"

  etcd2:
    name: {{ETCD_NODE_NAME}}
    initial-cluster: {{ETCD_INITIAL_CLUSTER}}
    advertise-client-urls: http://$private_ipv4:2379
    listen-client-urls: http://0.0.0.0:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-peer-urls: http://$private_ipv4:2380

  units:

  - name: etcd2.service
    command: start
  - name: zscaler_certs.service
    content: |
      [Unit]
      AssertPathExists=/etc/ssl/certs/zscaler1.pem
      AssertPathExists=/etc/ssl/certs/zscaler2.pem
      [Service]
      Type=oneshot
      ExecStart=/usr/sbin/update-ca-certificates
      RemainAfterExit=true
      StandardOutput=journal
  - name: zscaler_certs.path
    command: start
    enable: true
    content: |
      [Path]
      PathExists=/etc/ssl/certs/zscaler1.pem
      PathExists=/etc/ssl/certs/zscaler2.pem

write_files:
- path: /etc/ssl/certs/zscaler1.pem
  permissions: "0644"
  owner: "root"
  content: |
    -----BEGIN CERTIFICATE-----
    MIIE0zCCA7ugAwIBAgIJANu+mC2Jt3uTMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYD
    4VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTERMA8GA1UEBxMIU2FuIEpvc2Ux
    FTATBgNVBAoTDFpzY2FsZXIgSW5jLjEVMBMGA1UECxMMWnNjYWxlciBJbmMuMRgw
    FgYDVQQDEw9ac2NhbGVyIFJvb3QgQ0ExIjAgBgkqhkiG9w0BCQEWE3N1cHBvcnRA
    enNjYWxlci5jb20wHhcNMTQxMjE5MDAyNzU1WhcNNDIwNTA2MDAyNzU1WjCBoTEL
    MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExETAPBgNVBAcTCFNhbiBK
    b3NlMRUwEwYDVQQKEwxac2NhbGVyIEluYy4xFTATBgNVBAsTDFpzY2FsZXIgSW5j
    LjEYMBYGA1UEAxMPWnNjYWxlciBSb290IENBMSIwIAYJKoZIhvcNAQkBFhNzdXBw
    b3J0QHpzY2FsZXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    qT7STSxZRTgEFFf6doHajSc1vk5jmzmM6BWuOo044EsaTc9eVEV/HjH/1DWzZtcr
    fTj+ni205apMTlKBW3UYR+lyLHQ9FoZiDXYXK8poKSV5+Tm0Vls/5Kb8mkhVVqv7
    LgYEmvEY7HPY+i1nEGZCa46ZXCOohJ0mBEtB9JVlpDIO+nN0hUMAYYdZ1KZWCMNf
    5J/aTZiShsorN2A38iSOhdd+mcRM4iNL3gsLu99XhKnRqKoHeH83lVdfu1XBeoQz
    z5V6gA3kbRvhDwoIlTBeMa5l4yRdJAfdpkbFzqiwSgNdhbxTHnYYorDzKfr2rEFM
    dsMU0DHdeAZf711+1CunuQIDAQABo4IBCjCCAQYwHQYDVR0OBBYEFLm33UrNww4M
    hp1d3+wcBGnFTpjfMIHWBgNVHSMEgc4wgcuAFLm33UrNww4Mhp1d3+wcBGnFTpjf
    oYGnpIGkMIGhMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTERMA8G
    A1UEBxMIU2FuIEpvc2UxFTATBgNVBAoTDFpzY2FsZXIgSW5jLjEVMBMGA1UECxMM
    WnNjYWxlciBJbmMuMRgwFgYDVQQDEw9ac2NhbGVyIFJvb3QgQ0ExIjAgBgkqhkiG
    9w0BCQEWE3N1cHBvcnRAenNjYWxlci5jb22CCQDbvpgtibd7kzAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAw0NdJh8w3NsJu4KHuVZUrmZgIohnTm0j+
    RTmYQ9IKA/pvxAcA6K1i/LO+Bt+tCX+C0yxqB8qzuo+4vAzoY5JEBhyhBhf1uK+P
    /WVWFZN/+hTgpSbZgzUEnWQG2gOVd24msex+0Sr7hyr9vn6OueH+jj+vCMiAm5+u
    kd7lLvJsBu3AO3jGWVLyPkS3i6Gf+rwAp1OsRrv3WnbkYcFf9xjuaf4z0hRCrLN2
    xFNjavxrHmsH8jPHVvgc1VD0Opja0l/BRVauTrUaoW6tE+wFG5rEcPGS80jjHK4S
    pB5iDj2mUZH1T8lzYtuZy0ZPirxmtsk3135+CKNa2OCAhhFjE0xd
    -----END CERTIFICATE-----

- path: /etc/ssl/certs/zscaler2.pem
  permissions: "0644"
  owner: "root:root"
  content: |
    -----BEGIN CERTIFICATE-----
    MIIE0zCCA7ugAwIBAgIJAOTYAq3C9SHKMA0GCSqGSIb3DQEBBQUAMIGhMQswCQYD
    VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTERMA8GA1UEBxMIU2FuIEpvc2Ux
    FTATBgNVBAoTDFpzY2FsZXIgSW5jLjEVMBMGA1UECxMMWnNjYWxlciBJbmMuMRgw
    FgYDVQQDEw9ac2NhbGVyIFJvb3QgQ0ExIjAgBgkqhkiG9w0BCQEWE3N1cHBvcnRA
    enNjYWxlci5jb20wHhcNMTMwNjI0MTU0NDE5WhcNNDAxMTA5MTU0NDE5WjCBoTEL
    MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExETAPBgNVBAcTCFNhbiBK
    b3NlMRUwEwYDVQQKEwxac2NhbGVyIEluYy4xFTATBgNVBAsTDFpzY2FsZXIgSW5j
    LjEYMBYGA1UEAxMPWnNjYWxlciBSb290IENBMSIwIAYJKoZIhvcNAQkBFhNzdXBw
    b3J0QHpzY2FsZXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    uTYftUd6FCweoWdu0hiJyt7js0OYTRoMheO6t1p64UHSjixHfcRa6G+jbEzjDtSP
    ZhbVZaTjQbDOvaVU8fyCazbwZBSmZy+UI4ILWLPywDL2FDDMkxqtNjL3UOHJKz8P
    UKPsj284kcWYmL4KZbclJk57oNdrkU/R0b3Oiqg76O+gcusxCvUgg4j2agxF5u89
    y3qFoZEUaZPGNUlFgF/61IK+BhaNuwDSnZ62K1WW5K8sd3/nUyjKvk4lbrZT1G48
    t20tbT0NGG3l5SNEulZfBruexiw+i5KH3FkI1gYmY1hXRKV4AHgBvefUDBSpVYgy
    TWjkRBDw3k9zXKtiTJ4x5wIDAQABo4IBCjCCAQYwHQYDVR0OBBYEFK1BqSokdBRw
    b5ob0IhuTRjBhkA2MIHWBgNVHSMEgc4wgcuAFK1BqSokdBRwb5ob0IhuTRjBhkA2
    oYGnpIGkMIGhMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTERMA8G
    A1UEBxMIU2FuIEpvc2UxFTATBgNVBAoTDFpzY2FsZXIgSW5jLjEVMBMGA1UECxMM
    WnNjYWxlciBJbmMuMRgwFgYDVQQDEw9ac2NhbGVyIFJvb3QgQ0ExIjAgBgkqhkiG
    9w0BCQEWE3N1cHBvcnRAenNjYWxlci5jb22CCQDk2AKtwvUhyjAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBBQUAA4IBAQAsglrucSDQjsNe8YaDj5ufMeWnWFlb5wfi
    prM4P2Gh0kjT0UqpIkFe7xE1UDvsT3XCFOc9YqF1Vz/XCea84qg6YW/uRPHNiYEw
    NeG0pN4WRoMngaSwwVAFuihzVmpg+lX813M314wwxnTY68Sh0AzI8Iit5XjNy+Mm
    x5AzyOOp03EvROg/jKbZlLAC5Q5kjCKXZtguCAuMemje7e+KVCJ1/Ihwg06vs4n1
    udJ08w1y9bxeML888S9hSpsSz0mJ+vULI5kBR2v2wGr5Q+TNezXZF2QY1Cxo7WaD
    gQmyaOJ89bZWRdtY1GjF3XCPD0ZlZ8wtCJH7pmDkX3WxRSI+6443
    -----END CERTIFICATE-----
