apiVersion: v1
kind: Pod
metadata:
  name: bounded-local-default
  annotations:
    launched_as: part_of_voltest
  labels:
    k8s-app: nginx
    voltestpod: "true"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: logging
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: logging
    flexVolume:
      driver: zopa.com/bounded-local
      fsType: ext4
  - name: podinfo
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: annotations
          fieldRef:
            fieldPath: metadata.annotations

---
apiVersion: v1
kind: Pod
metadata:
  name: bounded-5g-500delay
  annotations:
    launched_as: part_of_voltest
  labels:
    k8s-app: nginx
    voltestpod: "true"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: logging
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: logging
    flexVolume:
      driver: zopa.com/bounded-local
      fsType: ext4
      options:
        size: "4096"
        cleanupDelay: "60"
        mirror: "true"
  - name: podinfo
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: annotations
          fieldRef:
            fieldPath: metadata.annotations
