apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    launched_as: part_of_voltest
  labels:
    k8s-app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: logging
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: logging
    flexVolume:
      driver: "zopa.com/splunk"
      fsType: "ext4"
  - name: podinfo
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: annotations
          fieldRef:
            fieldPath: metadata.annotations
