apiVersion: v1
kind: Pod
metadata:
  name: logging-test1
  annotations:
    launched_as: part_of_voltest
  labels:
    k8s-app: random_logger
    voltestpod: "true"
spec:
  containers:
  - name: logtest1
    image: davidmccormick/random_log_generator
    volumeMounts:
    - name: logging
      mountPath: /logs
  volumes:
  - name: logging
    flexVolume:
      driver: zopa.com/bounded-local
      fsType: ext4
      options:
        size: "4096"
        cleanupDelay: "60"
        logCollectCopy: "true"
  - name: podinfo
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: annotations
          fieldRef:
            fieldPath: metadata.annotations
---
apiVersion: v1
kind: Pod
metadata:
  name: logging-test2
  annotations:
    launched_as: part_of_voltest
  labels:
    k8s-app: random_logger
    voltestpod: "true"
spec:
  containers:
  - name: logtest2
    image: davidmccormick/random_log_generator
    volumeMounts:
    - name: logging
      mountPath: /logs
    args: 
    - /bin/sh
    - -c
    - "mkdir -p /logs/ApplicationXXX; /log_generator.py --logFile=/logs/ApplicationXXX/star.log"
  volumes:
  - name: logging
    flexVolume:
      driver: zopa.com/bounded-local
      fsType: ext4
      options:
        size: "4096"
        cleanupDelay: "60"
        logCollectCopy: "true"
  - name: podinfo
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: annotations
          fieldRef:
            fieldPath: metadata.annotations
